sudo: true
cache:
  directories:
  - $HOME/.m2
  
language: java
jdk:
  - oraclejdk8
# workaround to specify custom Maven options to run the JUnit tests with Elasticsearch
# see https://github.com/travis-ci/travis-ci/issues/1689
before_script:
  - export MAVEN_SKIP_RC="true"
  - export MAVEN_OPTS="-ea"
script:
  - mvn test -B -Dtests.security.manager=false
